### PR TITLE
Added support for dynamic ip

### PR DESCRIPTION
**Pull request by kennylam777**
The intention to enable udp2raw-tunenl with dynamic ip address by hostname is to support udp2raw-tunenl to run on Docker.

**For exeample** a server hosting 2 running Docker images - udp2raw-tunnel + OpenVPN, the status of those continaer would like this initially:
OpenVPN : 10.0.0.1
udp2raw-tunnel : 10.0.0.2

Then the command line should be  :  udp2raw_dynamic -s -l 0.0.0.0:12345 -r 10.0.0.1:1194

Due to some reason, may be upgrading the docker image, which is a very common action in Docker enviroment, and then the changing of IP address of OpenVPN container (10.0.0.1 -> 10.0.0.3) will cause the running udp2raw-tunnel image pointing to a dead container and result failed connection in the system.

By applying this patch, the command line can be : udp2raw_dynamic -s -l 0.0.0.0:12345 -r openvpn:1194
and then link the OpenVPN's container to udp2raw-tunnel's container as hostname "openvpn". I had tested this patch with my Docker environment with changing IPs in the containers.

This patch included dynamic IP support for client mode just like the server mode, so that a server with hostname of dynamic IP address can be used too.

Previously I made a wrapper script to resolve the destination container ip before launching udp2raw_dynamic , but I found that it is better to let dns resolving be done when 1. Connection to remote was made (Server mode) 2. Heartbeat failed and trying to reconnect (Client mode)

**Chinese in short**
寫這個Patch的原因是, 我自己是在Docker環境跑udp2raw-tunnel, 但Docker下的Container的IP會改變, 不得不手動重啟udp2raw-tunnel的container才能resolve到新的IP, 不可靠。

### CODE REVIEW

**Comment by wangyu-** [comment]
Hi,thanks for the patch.
Currently there is a problem for server.This programs use epoll to handle multi connections,it only has a single thread.`gethostbyname` is a blocking opeation,though it is called for every new connection only one time,it can still block other existing connections.

**Comment by kennylam777** [comment]
Thanks for the suggestion 👍 , I will take a look into it, at least make it as an switchable option.

**Comment by kennylam777** [comment]
Before I found a safe way to update the "remote_ip_uint32" variable from separated thread, I just removed gethostbyname() relateds code in both client_on_timer() and server_on_raw_recv_ready()

**Comment by wangyu-** [comment]
merged, thanks for the patch.

```
+	struct hostent        *he;
+	if ( (he = gethostbyname(remote_host) ) == NULL ) {
+		mylog(log_error,"Unable to resolve hostname: %s\n",remote_host);
+		exit(1); /* error */
+	}
+	struct in_addr **addr_list = (struct in_addr **)he->h_addr_list;
+	remote_ip_uint32=(*addr_list[0]).s_addr;
```

Maybe there is a small problem, `gethostbyname()` may return both ipv4 and ipv6 address,  I will fix it later by myself before next release.

**Comment by wangyu-** [comment]
This patch causes a warning at compile time:

```
/tmp/cc0z371h.o: In function `main':
/root/Desktop/udp2raw-tunnel/main.cpp:1770: warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

details at:
https://stackoverflow.com/questions/15165306/compile-a-static-binary-which-code-there-a-function-gethostbyname

As a result ,the portablity of binary will be affected:

If you compile/cross compile udp2raw on a PC with glibc, it doesnt run correcly on a raspberry pi / openwrt x86 router(the `gethostbyname()` function fails with NO_RECOVERY). But if you compile it locally on raspberry pi, it runs with no problem. 

The solution is not easy:  
1.You have to compile glibc(not merely udp2raw) with `--enable-static-nss` enabled 
2. or drop glibc support and switch to musl libc.
3. or link to a 3rd party dns-resolver lib. 

So, I disabled this feature by default. For safety I disabled it at compile time. To enable this feature use : `make OPT=-DENABLE_DNS_RESOLVE`.

**Pull request merged**
