### PR TITLE
Added DNS lookup on launch

### PR DESCRIPTION
**Pull request by jqqqqqqqqqq**
Resolve the first ip from DNS lookup result, and set it as remote ip.

Supports A and AAAA records.

### CODE REVIEW

**Comment by jqqqqqqqqqq** [comment]
```
warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
This warning still persists and there is no way to bypass glibc I'm afraid.

But by only resolve the DNS record once, there will be no more performance issue.

Random thought on DDNS support: 

- Use crontab to schedule periodic restart

**Comment by freeyoung** [comment]
Speaking of DDNS, see https://github.com/wangyu-/udp2raw-tunnel/pull/66

**Comment by Curtis-Jiang-2020** [comment]
@freeyoung  Old support is ipv4 only I'm afraid. But I'm closing this pr since I no longer use this project.

**Comment by jqqqqqqqqqq** [comment]
@freeyoung I'm closing this pr because I no longer use this project. I'm afraid the old implementation only support ipv4, but indeed it makes this pr useless in someway.

**Pull request closed without merging**
