### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by jiangtiandao**
I hope you can provide offical images like https://hub.docker.com/r/xtaci/kcptun/

### CODE REVIEW

**Comment by wangyu-** [comment]
merged,thx

I will check hub.docker.com later.

**Comment by jiangtiandao** [comment]
Click create on left up corner then create automated-build 
default

**Comment by wangyu-** [comment]
Done,using following instructions to run:

`docker pull wangyucn/udp2raw-tunnel`

`docker run --net=host --cap-add=NET_ADMIN wangyucn/udp2raw-tunnel /bin/udp2raw_dynamic -c -r44.55.66.77:9000 -l 127.0.0.1:6000 --raw-mode faketcp  --lower-level auto -a -k xxxxxxxx

==note==
It may not run correctly under windows/macOS by default,because docker relys on virtualBox under a non-Linux host.

To run correctly you may have to manually change the network mode of underlying virtualBox to bridged.

**Comment by wangyu-** [comment]
Done,using following instructions to run:

`docker pull wangyucn/udp2raw-tunnel`

`docker run --net=host --cap-add=NET_ADMIN wangyucn/udp2raw-tunnel /bin/udp2raw_dynamic -c -r44.55.66.77:9000 -l 127.0.0.1:6000 --raw-mode faketcp  --lower-level auto -a -k xxxxxxxx`

==note==
It may not run correctly under windows/macOS by default,because docker relys on virtualBox under a non-Linux host.

To run correctly you may have to manually change the network mode of underlying virtualBox to bridged.

**Pull request merged**
